### ISSUE TITLE
[RFC] Public Roadmap

### ISSUE THREAD

**Issue by sk-** [sk-/git-lint#152]
First of all, thanks for trusting this project and for all the contributions you have made. I apologize if I haven't been the most diligent dealing with open PRs and Issues, and as such I want to consult with the community what they think should be the objective for a next major release.

Based on my own ideas and what I've seen in the Issue tracker I think the requirements are the following:

- [ ] Remove support for Python 2 and Python 3.4 or earlier, as those versions are no longer supported.
- [ ] Remove included git hooks, as these are not platform agnostic.
- [ ] Remove default configuration and bundled linters. Static analysis is thankfully evolving quite fast, so providing and maintaining an up-to date and comprehensive list of linters, is much more work that a single person could handle. Also, it makes the testing much slower and fragile, as dependencies are usually changing. The idea would be to have a wiki with user contributed recipes. Or alternatively a way of pulling recipes from github. Something like `git-lint-configure @sk-/git-lint-pylint @user/git-lint-eslint`. 
- [ ] Add types to codebase.
- [ ] Improve cache management. Detect when config changed, and allow to skip the cache.
- [ ] Improve command line. Better options and documentation flags, plain output for CI, etc.
- [ ] Improve calling api, so that it's easier to integrate with CI systems.
- [ ] Provide base Github action. One would need to extend it to install the linters used in the project #139
- [ ] Change the config declaration file. I find yaml to be quite inadequate for this purposes as ones needs to escape some characters and multiline support is not the best.

Let me know what you think and how you are using the project.

**Comment by thibaut-singlefile** [comment]
Just discovered this project today. It is a great fit for what we are trying to do.
I was looking for eslint support and this would work great for us:
> Or alternatively a way of pulling recipes from github. Something like git-lint-configure @sk-/git-lint-pylint @user/git-lint-eslint.

**Comment by thibaut-singlefile** [comment]
We actually found https://pre-commit.com/ that supports a way to pull recipes from Github: https://pre-commit.com/hooks.html

**Comment by sk-** [comment]
@thibaut-singlefile Note that pre commit is similar in that it will check modified files, however they do not report changes on modified lines, which is one of the core value propositions of `git-lint`. 

I guess that given the adoption of `pre-commit`, one could add support for their configuration files.

**Comment by bac** [comment]
@sk- Thanks for opening this Roadmap dialogue.  My first request for going forward would be to get the release process in order and make the necessary updates people are asking for.  And act on the PRs that people have put up.

From your list, I'd prioritize dropping py2 and cache management.

**Comment by sk-** [comment]
Thanks @bac for the feedback, unfortunately I've decided to deprecate this package. Below is what I wrote on the README.

DEPRECATED
==========

Unfortunately I've decided to deprecate this package.

* `git-lint` would be more valuable to large companies with large legacy codebases. But for smaller ones, it's quite possible (I've done it in many) to progressively make the linter config stricter. 
* Users of this project wanted to have a complete out of the box experience, while my original vision was that companies/users would define their own configuration, tailoring to whatever settings and linters they wanted.
* There was not really much feedback on the RFC issue https://github.com/sk-/git-lint/issues/152
* There are some promising tools, like https://pre-commit.com/ which has an ever growing adoption rate. It's not a full replacement of `git-lint`, but at least would lint only modified files.
